### PR TITLE
MNT: Re-rendered with conda-smithy 2.4.2

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by sannykr** [comment]
@ocefpaf : Could you please review the changes and merge.

**Comment by sannykr** [comment]
@ocefpaf : I am trying to build version 2.10.2.  Could you please make a branch(2.10.x) on the feedstock to build 2.10.2.     I don't want to make a pull request on master and downgrade it.

**Comment by sannykr** [comment]
@ocefpaf : following up

**Comment by ocefpaf** [comment]
I'm traveling with limited access to my  laptop. I can merge stuff but more complex things will have to wait.

**Comment by sannykr** [comment]
@ocefpaf : I am sorry to bother you. I will wait for that. 
@kwilcox

**Comment by kwilcox** [comment]
It is worth saying that it would have been MUCH easier to do this if you had not included the bump to `2.11.1` in the re-render commit. Please separate them in the future!

**Comment by kwilcox** [comment]
@sannykr this is all set, 2.10.2 is available now

**Pull request merged**
